function dados = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  DADOS = IMPORTFILE1(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  DADOS = IMPORTFILE1(FILE, SHEET) reads from the specified worksheet.
%
%  DADOS = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  dados = importfile1("C:\Users\lucia\OneDrive\Área de Trabalho\Unisinos\Projeto Sapinhoá\Porosidades_3D\Scripts\Teste_regressão_porosidades - Copia\Arvores_de_Regressão\dados.xlsx", "Planilha1", [2, 2525]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Aug-2022 17:25:50

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2525];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["AMPCONS", "INSPHASE", "RAI", "FLAT", "SWT", "NMRT_Final"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
dados = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    dados = [dados; tb]; %#ok<AGROW>
end

%% Convert to output type
dados = table2array(dados);
end