function poco = importacao(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BRSA594SPS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  BRSA594SPS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  BRSA594SPS = importfile("C:\Users\lucia\OneDrive\Área de Trabalho\Unisinos\Projeto Sapinhoá\Porosidades_3D\Scripts\Teste_regressão_porosidades\Pocos_atrib_poros\1-BRSA-594-SPS.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Aug-2022 15:17:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["MD", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "AMPCONS", "INSPHASE", "RAI", "Var11", "FLAT", "SWT", "Var14", "Var15", "NMRT_Final"];
opts.SelectedVariableNames = ["MD", "AMPCONS", "INSPHASE", "RAI", "FLAT", "SWT", "NMRT_Final"];
opts.VariableTypes = ["double", "char", "char", "char", "char", "char", "char", "double", "double", "double", "char", "double", "double", "char", "char", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var11", "Var14", "Var15"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var11", "Var14", "Var15"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["MD", "INSPHASE", "RAI", "SWT"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["MD", "INSPHASE", "RAI", "SWT"], "ThousandsSeparator", ",");

% Import the data
poco = readtable(filename, opts);

%% Convert to output type
poco = table2array(poco);
end